# Generated by Django 2.2.4 on 2019-08-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('eta', models.DateTimeField()),
                ('etd', models.DateTimeField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callsmanager.Port')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callsmanager.Ship')),
            ],
        ),
    ]
