# Generated by Django 2.2.4 on 2019-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsmanager', '0002_auto_20190809_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='etd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
