# Generated by Django 2.2.4 on 2019-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsmanager', '0003_auto_20190809_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='call_count',
            field=models.IntegerField(default=0),
        ),
    ]
