# Generated by Django 2.2.4 on 2019-08-17 06:34

import callsmanager.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callsmanager', '0004_port_call_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='move_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='call',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ship',
            name='imo',
            field=models.IntegerField(validators=[callsmanager.validators.validate_IMO]),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('target_berth', models.CharField(max_length=10)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callsmanager.Call')),
                ('prevMove', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callsmanager.Move')),
            ],
        ),
    ]
